### ISSUE TITLE
Server not loading page on start

### ISSUE THREAD

**Issue by balihoo-aharl** [balihoo/balihoo-creative#2]
~~The console doesn't appear to work with the latest stable version of Node.~~

It actually appears that the server is not launching the template index page on start. The server appears to work normally if you manually put http://localhost:8088 in your browser.

I was mistakenly trying to use #console based on a screenshot in the tutorial documentation to load the console.

**Comment by balihoo-aharl** [comment]
@balihoo-pprice I did some testing locally, and this appears to have broken in Node 0.11.11

**Comment by balihoo-dgoldston** [comment]
In Safari, the project launches as `http://localhost:::8088/$console` node v0.12.1

**Comment by balihoo-pprice** [comment]
Starting the server should load you into http://localhost:8088/$console
I'm trying it on a mac in safari and it is working fine, so I'm guessing there is an issue in this line of code: https://github.com/balihoo/balihoo-creative/blob/master/src/server.coffee#L122-L123
addr.address seems to be resolving to localhost::
I'll see if I can figure out a better way to determine the local address, or just hard-code it to localhost.

**Comment by balihoo-pprice** [comment]
@balihoo-aharl , I'll get a system or a virtual that runs 12.2 and do some testing.

**Comment by AndyCobb** [comment]
Various issues with opened tab fixed in cd3c8e3ab268502eadff627ba5e4fd53b9a3068a
